# Generated by Django 4.0 on 2021-12-22 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoSolicitacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload', models.FileField(max_length=255, upload_to='solicitacao_documentos')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome Documento')),
                ('tipo', models.CharField(max_length=80, verbose_name='Categoria/Tipo')),
            ],
            options={
                'verbose_name': 'Documento Solicitacao',
                'verbose_name_plural': 'Documentos Solicitacao',
            },
        ),
        migrations.CreateModel(
            name='Solicitacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoSolicitacao', models.CharField(max_length=120, verbose_name='Tipo de Solicitação')),
                ('data', models.DateTimeField()),
                ('status', models.BooleanField(default=True)),
                ('deferida', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Solicitação',
                'verbose_name_plural': 'Solicitações',
            },
        ),
    ]
