# Generated by Django 4.0 on 2021-12-19 22:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=255)),
                ('nome', models.CharField(max_length=255)),
                ('genero', models.CharField(max_length=10, verbose_name='Genero')),
                ('cpf', models.CharField(max_length=50, unique=True, verbose_name='CPF')),
                ('rg', models.CharField(max_length=50, verbose_name='RG')),
                ('cnh', models.CharField(max_length=50, verbose_name='CNH')),
                ('pis_pasep', models.CharField(max_length=100, verbose_name='PIS/PASEP')),
                ('dataNascimento', models.DateField(blank=True, null=True, verbose_name='Data de Nascimento')),
                ('eleitorNumero', models.CharField(max_length=50, verbose_name='Número de eleitor')),
                ('nomeMae', models.CharField(max_length=100, verbose_name='Nome da Mãe')),
                ('nomePai', models.CharField(max_length=100, verbose_name='Nome do Pai')),
                ('naturalidade', models.CharField(max_length=100, verbose_name='Naturalidade')),
                ('cargo', models.CharField(max_length=100, verbose_name='Cargo')),
                ('foto', models.ImageField(upload_to='user_foto')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=100, verbose_name='Estado')),
                ('cidade', models.CharField(max_length=100, verbose_name='Cidade')),
                ('numero', models.CharField(max_length=10, verbose_name='Número')),
                ('rua', models.CharField(max_length=150, verbose_name='Rua/Avenida')),
                ('bairro', models.CharField(max_length=80, verbose_name='Bairro')),
                ('complemento', models.CharField(max_length=100, verbose_name='Complemento')),
                ('cep', models.CharField(max_length=15, verbose_name='CEP')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='endereco', to='user.user')),
            ],
            options={
                'verbose_name': 'Endereço',
            },
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload', models.FileField(max_length=255, upload_to='user_documentos')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome Documento')),
                ('tipo', models.CharField(max_length=80, verbose_name='Categoria/Tipo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documento', to='user.user')),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
            },
        ),
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefone', models.CharField(max_length=50, verbose_name='Telefone')),
                ('celular', models.CharField(max_length=50, verbose_name='Celular')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contato', to='user.user')),
            ],
            options={
                'verbose_name': 'Contato',
                'verbose_name_plural': 'Contatos',
            },
        ),
    ]
