# Generated by Django 4.0 on 2021-12-18 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=255)),
                ('nome', models.CharField(max_length=255)),
                ('genero', models.CharField(max_length=10, verbose_name='Genero')),
                ('cpf', models.CharField(max_length=50, unique=True, verbose_name='CPF')),
                ('rg', models.CharField(max_length=50, verbose_name='RG')),
                ('cnh', models.CharField(max_length=50, verbose_name='CNH')),
                ('pis_pasep', models.CharField(max_length=100, verbose_name='PIS/PASEP')),
                ('dataNascimento', models.DateField(blank=True, null=True, verbose_name='Data de Nascimento')),
                ('eleitorNumero', models.CharField(max_length=50, verbose_name='Número de eleitor')),
                ('nomeMae', models.CharField(max_length=100, verbose_name='Nome da Mãe')),
                ('nomePai', models.CharField(max_length=100, verbose_name='Nome do Pai')),
                ('naturalidade', models.CharField(max_length=100, verbose_name='Naturalidade')),
                ('cargo', models.CharField(max_length=100, verbose_name='Cargo')),
                ('foto', models.ImageField(upload_to='user_foto')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
