# Generated by Django 4.0 on 2021-12-18 22:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=100, verbose_name='Estado')),
                ('cidade', models.CharField(max_length=100, verbose_name='Cidade')),
                ('numero', models.CharField(max_length=10, verbose_name='Número')),
                ('rua', models.CharField(max_length=150, verbose_name='Rua/Avenida')),
                ('bairro', models.CharField(max_length=80, verbose_name='Bairro')),
                ('complemento', models.CharField(max_length=100, verbose_name='Complemento')),
                ('cep', models.CharField(max_length=15, verbose_name='CEP')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='endereco', to='user.user')),
            ],
            options={
                'verbose_name': 'Endereço',
            },
        ),
    ]
