# Generated by Django 4.0 on 2021-12-23 22:47

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='foto',
            field=models.ImageField(null=True, upload_to=user.models.image_file_path),
        ),
    ]
